name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload config
        uses: actions/upload-artifact@v4
        with:
          name: custom markdownlint config
          path: ./.github/config/custom.markdownlint.jsonc
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          fix: true
          config: './.github/config/custom.markdownlint.jsonc'
          globs: '**/*.md'
